apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.12.0
    chart: keda
    helm:
      values: |
        crds:
          install: true
        crds:
          install: false
        operator:
          replicaCount: 1
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
        metricsServer:
          replicaCount: 1
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: scaledjobs.keda.sh
      jsonPointers:
        - /metadata/annotations