apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argo
spec:
  project: default
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.11.2
    helm:
      values: |
        crds:
          install: true
          preserve: true
        operator:
          replicaCount: 1
        metricsServer:
          replicaCount: 1
        rbac:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true