apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/red512/vimex-gitops.git
    targetRevision: HEAD
    path: gitops/environments/staging/keda-helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: scaledjobs.keda.sh
      jsonPointers:
        - /metadata/annotations