apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-crds
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/kedacore/keda.git
    targetRevision: v2.11.2
    path: config/crd
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: false  # Don't prune CRDs
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations