# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-deployment
#   namespace: flask-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: projectred521/flask-ip:latest
#         resources:
#           limits:
#             memory: "256Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 5000
