apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: flask-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment  # Update this with your actual Deployment name
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
