apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: {{ .Values.namespace.name }}
  labels:
    app: celery-worker
spec:
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["celery", "-A", "app.celery", "worker", "--loglevel=info"]
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: api-key
                key: API-KEY
          - name: CELERY_BROKER_URL
            value: "redis://redis-service:6379/0"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis-service:6379/0"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"