apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  namespace: {{ .Values.namespace.name }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      canaryService: backend-service-canary
      stableService: backend-service
      trafficRouting:
        nginx:
          stableIngress: backend-ingress
      steps:
      - setWeight: 20
      - pause: {duration: 5s}
      - setWeight: 50
      - pause: {duration: 5s}
      - setWeight: 80
      - pause: {duration: 10s}
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 2
        args:
        - name: service-name
          value: backend-service
      scaleDownDelaySeconds: 300  # 5 minutes delay before scaling down
      scaleDownDelayRevisionLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 5000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key
                  key: API-KEY
            - name: CELERY_BROKER_URL
              value: "redis://redis-service:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis-service:6379/0"
          startupProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - 'celery -A app.celery inspect ping'
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - 'celery -A app.celery inspect active'
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - 'celery -A app.celery inspect ping'
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3


