apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backend-scaler
  namespace: {{ .Values.namespace.name }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: backend
  pollingInterval: 30
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
  - type: redis
    metadata:
      address: redis://redis:6379
      listName: celery
      listLength: "5"
      enableTLS: "false"
      activationListLength: "1"