apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backend-scaledobject
  namespace: {{ .Values.namespace.name }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: backend
  pollingInterval: 30
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 2
  triggers:
  - type: redis
    metadata:
      address: argocd-redis.argo.svc.cluster.local:6379
      listName: task_queue
      listLength: "3"
      activationListLength: "1"