apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-key
  namespace: backend
spec:
  encryptedData:
    API-KEY: {{ .Values.apiKey.key }}
  template:
    metadata:
      name: api-key
      namespace: backend
    type: Opaque