apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: backend  
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}