---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/red512/vimex-gitops
    targetRevision: HEAD
    path: gitops/helm/backend-helm-chart
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true