apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/red512/vimex-gitops.git
    targetRevision: HEAD
    path: gitops/helm/redis-helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true