apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/red512/vimex-gitops.git
    targetRevision: HEAD
<<<<<<< HEAD
    path: gitops/helm/redis-helm-chart
=======
    path: gitops/redis-helm-chart
>>>>>>> 75370cde4569dbce929a3b20773ed8a78cf0eb70
  destination:
    server: https://kubernetes.default.svc
    namespace: backend  # Same namespace as your application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true