{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: worker
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 15  # Check every 15 seconds
  cooldownPeriod: 60   # Wait 1 minute before scaling down
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
    - type: redis
      metadata:
        address: "redis://redis-redis-chart:6379"
        listName: {{ .Values.autoscaling.redis.queueName | default "celery" | quote }}
        listLength: {{ .Values.autoscaling.redis.targetQueueLength | default "5" | quote }}
        activationListLength: "1"
        databaseIndex: "0"
        enableTLS: "false"
{{- end }}