apiVersion: v2
name: prometheus-helm-chart
description: Simple Prometheus server for staging
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: prometheus
    version: 25.24.1
    repository: https://prometheus-community.github.io/helm-charts