prometheus:
  server:
    replicaCount: 1
    retention: "7d"
    persistentVolume:
      enabled: true
      size: 5Gi
    service:
      type: ClusterIP
      servicePort: 80

  # Disable AlertManager
  alertmanager:
    enabled: false

  # Disable node exporter (not needed for basic metrics)
  nodeExporter:
    enabled: false

  # Disable kube state metrics (not needed for basic metrics)
  kubeStateMetrics:
    enabled: false

  # Disable pushgateway (not needed)
  pushgateway:
    enabled: false

  # Simple scrape configs for basic monitoring
  serverFiles:
    prometheus.yml:
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'kubernetes-pods'
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              target_label: __address__