keda:
  crds:
    install: true
    preserve: true
    wait: true      # Wait for CRDs to be established before proceeding

  metricsServer:
    replicaCount: 1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "50m"

  operator:
    replicaCount: 1
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
      requests:
        memory: "128Mi"
        cpu: "100m"
    
    rbac:
      create: true

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000

  serviceAccount:
    create: true

  watchNamespace: ""  # Watch all namespaces